# Generated by Django 3.2.12 on 2022-03-28 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nlp0', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summarytext',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='summarytext',
            name='votes',
        ),
        migrations.AddField(
            model_name='summarytext',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='originaltext',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
